
username: 'hackermotto'
email: 'root@hackermotto.com'
password: ''
phone: ''
login_service: 'Twitter'
cookies: ''
driver: 'Firefox'
headless: true

post_black_list:
  - 'Sex'
  - 'Drugs'
  - 'Child Labor'

clap_for_posts: true
randomize_clapping_for_posts: false
max_claps_for_post: 45
min_claps_for_post: 20

comment_on_posts: true
randomize_commenting_on_posts: false
comments: 
  - 'Great Post.'
  - 'Great Read!'
  - 'Good work keep it up!'
  - 'Really enjoyed the content!'
  - 'Very interesting!'

follow_users: true
randomize_following_users: false

unfollow_users: false
randomize_unfollowing_users: false
unfollow_users_black_list: 
  - 'DontUnfollowMe'

use_related_topics: true
posts_per_topic: 50
verbose: true

max_sleep: 15
min_sleep: 10

timeout: 60

logging_level: "INFO"
logging_datefmt: "%m/%d/%Y %H:%M:%S"
logging_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
logging_file: "mediumbot.log"

